WK.TechnicalTest.Web/Models/ErrorViewModel.cs
namespace WK.TechnicalTest.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WK.TechnicalTest.Web/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using WK.TechnicalTest.BLL.Interfaces.Services;
using WK.TechnicalTest.Web.ViewModel.Category;
using WK.TechnicalTest.Web.ViewModel.Pages;
using WK.TechnicalTest.Web.ViewModel.Product;

namespace WK.TechnicalTest.Web.Controllers
{
    public class CategoryController : MainController
    {
        private readonly IApiService _apiService;

        public CategoryController(IApiService apiService) : base(apiService)
        {
            _apiService = apiService;
        }

        [HttpPost]
        public async Task<IActionResult> SaveCategory(CategoryInputViewModel categoryInputViewModel)
        {
            IEnumerable<string> errors;
            if (categoryInputViewModel.Id > 0)
            {
                errors = await _apiService.Update("category", categoryInputViewModel.Id, JsonConvert.SerializeObject(categoryInputViewModel));
            }
            else
            {
                errors = await _apiService.Add("category", JsonConvert.SerializeObject(categoryInputViewModel));
            }

            return RedirectToAction("Index", "Home", string.Join("<br/>", errors));
        }

        [HttpGet]
        public async Task<IActionResult> GetCategory(long categoryId)
        {
            CategoryResponseViewModel category = (CategoryResponseViewModel)await _apiService.GetById("category", typeof(CategoryResponseViewModel), categoryId);

            return new JsonResult(category);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteCategory(long categoryId)
        {
            bool success = await _apiService.Delete("category", categoryId);

            return new JsonResult(new { success });
        }

    }
}

WK.TechnicalTest.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Diagnostics;
using WK.TechnicalTest.BLL.Interfaces.Services;
using WK.TechnicalTest.Web.ViewModel.Category;
using WK.TechnicalTest.Web.ViewModel.Pages;
using WK.TechnicalTest.Web.ViewModel.Product;

namespace WK.TechnicalTest.Web.Controllers
{
    public class HomeController : MainController
    {

        public HomeController( IApiService apiService) : base(apiService)
        {
        }

        public async Task<IActionResult> Index(string errors)
        {
            HomeViewModel viewModel = await GetViewModel(errors);

            return View(viewModel);
        }
    }
}

WK.TechnicalTest.Web/Controllers/MainController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using WK.TechnicalTest.BLL.Interfaces.Services;
using WK.TechnicalTest.Web.ViewModel.Category;
using WK.TechnicalTest.Web.ViewModel.Pages;
using WK.TechnicalTest.Web.ViewModel.Product;

namespace WK.TechnicalTest.Web.Controllers
{
    public class MainController : Controller
    {
        private readonly IApiService _apiService;

        public MainController(IApiService apiService)
        {
            _apiService = apiService;
        }

        protected async Task<HomeViewModel> GetViewModel(string errors = null)
        {
            var categories = JsonConvert.DeserializeObject<IEnumerable<CategoryResponseViewModel>>(await _apiService.GetAll("category"));
            var products = JsonConvert.DeserializeObject<IEnumerable<ProductResponseViewModel>>(await _apiService.GetAll("product"));

            return new HomeViewModel()
            {
                Categories = categories,
                Products = products,
                SelectCategory = new SelectList(categories, "Id", "Name"),
                Errors = errors
            };
        }
    }
}

WK.TechnicalTest.Web/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using WK.TechnicalTest.BLL.Interfaces.Services;
using WK.TechnicalTest.Web.ViewModel.Category;
using WK.TechnicalTest.Web.ViewModel.Pages;
using WK.TechnicalTest.Web.ViewModel.Product;

namespace WK.TechnicalTest.Web.Controllers
{
    public class ProductController : MainController
    {
        private readonly IApiService _apiService;

        public ProductController(IApiService apiService) : base(apiService)
        {
            _apiService = apiService;
        }

        [HttpPost]
        public async Task<IActionResult> SaveProduct(ProductInputViewModel productInputViewModel)
        {
            IEnumerable<string> errors;
            if (productInputViewModel.Id > 0)
            {
                errors = await _apiService.Update("product", productInputViewModel.Id, JsonConvert.SerializeObject(productInputViewModel));
            }
            else
            {
                errors = await _apiService.Add("product", JsonConvert.SerializeObject(productInputViewModel));
            }

            return RedirectToAction("Index", "Home", string.Join("<br/>", errors));
        }

        [HttpGet]
        public async Task<IActionResult> GetProduct(long productId)
        {
            ProductResponseViewModel product = (ProductResponseViewModel)await _apiService.GetById("product", typeof(ProductResponseViewModel), productId);

            return new JsonResult(product);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteProduct(long productId)
        {
            bool success = await _apiService.Delete("product", productId);

            return new JsonResult(new { success });
        }

    }
}

WK.TechnicalTest.Web/Views/Home/Index.cshtml
@using WK.TechnicalTest.Web.ViewModel.Pages;
@model HomeViewModel;
@{
    ViewData["Title"] = "Home";
}

@section Styles{
    <link rel="stylesheet" href="~/css/jquery.dataTables.min.css" asp-append-version="true" />

    <style>
        .entity-title {
            height: 55px;
            width: 100%;
            border-radius: 7px;
            display: flex;
            align-items: center;
            justify-content: center;
            font-size: 20px;
            font-weight: 700;
            text-decoration: none;
            color: white;
        }

            .entity-title:hover {
                color: white;
            }

            .entity-title.primary-color {
                background: black;
                border: black;
            }

            .entity-title.secondary-color {
                background: #ed233d;
                border: #ed233d;
            }

        @@media(max-width:991px) {
            .entity-title {
                margin-top: 30px;
            }
        }

        /*DataTable*/
        .dataTables_length select {
            border-radius: 7px;
            height: 35px;
            width: 60px;
        }

        input[type="search"] {
            border-radius: 7px;
            border: 1px solid;
            height: 35px;
        }

        #categoriesTable_paginate.dataTables_paginate .paginate_button:hover {
            background: #111 !important;
        }

        .dataTables_wrapper .dataTables_paginate .paginate_button.current, .dataTables_wrapper .dataTables_paginate .paginate_button.current:hover {
            background: #909090 !important;
            color: #fff !important;
        }

        .edit, .delete {
            cursor: pointer;
        }

        .btn-save {
            background: #ED233D;
            color: white;
        }
    </style>
}

    <div class="row">
        <div class="col-12">
            <span style="color:#ED233D; font-size:48px; font-weight:700;">Bem-vindo</span>
        </div>
    </div>
    <div class="row mt-5">
        <div class="col-lg-6 col-12">
            <button id="btnNewCategory" class="entity-title primary-color">
                Nova Categoria
            </button>

            <div class="table-wrap mt-4">
                <table id="categoriesTable" class="table">
                    <thead>
                        <tr>
                            <th class="text-center">Nome</th>
                            <th class="text-center">
                                Ações
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var category in Model.Categories)
                    {
                        <tr>
                            <td class="text-center">@category.Name</td>
                            <td class="acoes text-center">
                                <a>
                                    <svg class="edit" data-id="@category.Id" xmlns="http://www.w3.org/2000/svg" width="19" height="19" viewBox="0 0 19 19" fill="none">
                                        <path d="M14.849 9.808L14.142 9.101L4.242 19.001H0V14.758L11.313 3.444L16.97 9.101C17.1575 9.28853 17.2628 9.54283 17.2628 9.808C17.2628 10.0732 17.1575 10.3275 16.97 10.515L9.9 17.586L8.485 16.172L14.849 9.808ZM12.728 7.687L11.313 6.273L2 15.586V17.001H3.414L12.728 7.687ZM15.556 0.615998L18.385 3.444C18.5725 3.63153 18.6778 3.88583 18.6778 4.151C18.6778 4.41616 18.5725 4.67047 18.385 4.858L16.97 6.273L12.728 2.03L14.142 0.615998C14.3295 0.428527 14.5838 0.323212 14.849 0.323212C15.1142 0.323212 15.3685 0.428527 15.556 0.615998Z" fill="#5C5C5C" />
                                    </svg> |
                                    <svg class="delete" data-id="@category.Id" xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 20 20" fill="none">
                                        <path d="M15 4H20V6H18V19C18 19.2652 17.8946 19.5196 17.7071 19.7071C17.5196 19.8946 17.2652 20 17 20H3C2.73478 20 2.48043 19.8946 2.29289 19.7071C2.10536 19.5196 2 19.2652 2 19V6H0V4H5V1C5 0.734784 5.10536 0.48043 5.29289 0.292893C5.48043 0.105357 5.73478 0 6 0H14C14.2652 0 14.5196 0.105357 14.7071 0.292893C14.8946 0.48043 15 0.734784 15 1V4ZM16 6H4V18H16V6ZM7 9H9V15H7V9ZM11 9H13V15H11V9ZM7 2V4H13V2H7Z" fill="#5C5C5C" />
                                    </svg>
                                </a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
    <div class="col-lg-6 col-12">
        <button id="btnNewProduct" class="entity-title secondary-color">
            Novo Produto
        </button>

        <div class="table-wrap mt-4">
            <table id="productsTable" class="table">
                <thead>
                    <tr>
                        <th class="text-center">Nome</th>
                        <th class="text-center">Nome da Categoria</th>
                        <th class="text-center">
                            Ações
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var product in Model.Products)
                    {
                        <tr>
                            <td class="text-center">@product.Name</td>
                            <td class="text-center">@product.CategoryName</td>
                            <td class="acoes text-center">
                                <svg class="edit" data-id="@product.Id" xmlns="http://www.w3.org/2000/svg" width="19" height="19" viewBox="0 0 19 19" fill="none">
                                    <path d="M14.849 9.808L14.142 9.101L4.242 19.001H0V14.758L11.313 3.444L16.97 9.101C17.1575 9.28853 17.2628 9.54283 17.2628 9.808C17.2628 10.0732 17.1575 10.3275 16.97 10.515L9.9 17.586L8.485 16.172L14.849 9.808ZM12.728 7.687L11.313 6.273L2 15.586V17.001H3.414L12.728 7.687ZM15.556 0.615998L18.385 3.444C18.5725 3.63153 18.6778 3.88583 18.6778 4.151C18.6778 4.41616 18.5725 4.67047 18.385 4.858L16.97 6.273L12.728 2.03L14.142 0.615998C14.3295 0.428527 14.5838 0.323212 14.849 0.323212C15.1142 0.323212 15.3685 0.428527 15.556 0.615998Z" fill="#5C5C5C" />
                                </svg>|
                                <svg class="delete" data-id="@product.Id" xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 20 20" fill="none">
                                    <path d="M15 4H20V6H18V19C18 19.2652 17.8946 19.5196 17.7071 19.7071C17.5196 19.8946 17.2652 20 17 20H3C2.73478 20 2.48043 19.8946 2.29289 19.7071C2.10536 19.5196 2 19.2652 2 19V6H0V4H5V1C5 0.734784 5.10536 0.48043 5.29289 0.292893C5.48043 0.105357 5.73478 0 6 0H14C14.2652 0 14.5196 0.105357 14.7071 0.292893C14.8946 0.48043 15 0.734784 15 1V4ZM16 6H4V18H16V6ZM7 9H9V15H7V9ZM11 9H13V15H11V9ZM7 2V4H13V2H7Z" fill="#5C5C5C" />
                                </svg>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

<div id="modalCategory" class="modal fade" role="dialog">

    <div class="modal-dialog">
        <div class="modal-content">
            <form asp-controller="Category" asp-action="SaveCategory" method="post">
                <div class="modal-header">
                    <h6 class="modal-title"></h6>
                </div>
                <div class="modal-body">
                    <input type="hidden" class="form-control form-control-sm pessoaId" />
                    <div class="form-group">
                        <input type="text" id="categoryName" name="Name" placeholder="Nome" class="form-control form-control-sm nome" />
                    </div>
                    <input type="hidden" id="categoryId" name="Id">
                </div>
                <div class="modal-footer">
                    <div class="form-group">
                        <input type="submit" value="Salvar" class="btn btn-sm btn-save" />
                        <input type="button" value="Cancelar" class="btn btn-sm btn-light" data-bs-dismiss="modal" />
                    </div>
                </div>
            </form>
        </div>
    </div>

</div>

<div id="modalProduct" class="modal fade" role="dialog">

    <div class="modal-dialog">
        <div class="modal-content">
            <form class="form-horizontal" asp-controller="Product" asp-action="SaveProduct" method="post">
                <div class="modal-header">
                    <h6 class="modal-title"></h6>
                </div>
                <div class="modal-body">
                    <input type="hidden" class="form-control form-control-sm pessoaId" />
                    <div class="form-group">
                        <input type="text" id="productName" name="Name" placeholder="Nome" class="form-control form-control-sm nome" />
                    </div>
                    <div class="form-group row mt-3">
                        <div class="col-6">
                            <select id="productCategoryId" class="form-control" name="CategoryId" asp-items="Model.SelectCategory">
                            </select>
                        </div>
                        <div class="col-6">
                            <input id="productPrice" type="number" class="form-control" placeholder="Preço" name="Price" />
                        </div>
                    </div>
                    <div class="form-group col-6">
                    </div>
                    <input type="hidden" id="productId" name="Id">
                </div>
                <div class="modal-footer">
                    <div class="form-group">
                        <input type="submit" value="Salvar" class="btn btn-sm btn-save" />
                        <input type="button" value="Cancelar" class="btn btn-sm btn-light" data-bs-dismiss="modal" />
                    </div>
                </div>
            </form>
        </div>
    </div>

</div>

@section Scripts {
    <script src="~/js/jquery.dataTables.min.js"></script>
    <script src="~/js/Category.js" asp-append-version="true"></script>
    <script src="~/js/Product.js" asp-append-version="true"></script>
    <script>
        $(document).ready(function() {
        @if (!string.IsNullOrEmpty(Model.Errors))
        {
            <text>
                    alert('@(Html.Raw(string.Join("<br/>", Model.Errors)))');
            </text>
        }

          var tableConfig = {
                language: {
                    "sEmptyTable": "Não foi encontrado nenhum registro",
                    "sLoadingRecords": "Carregando...",
                    "sProcessing": "Processando...",
                    "sLengthMenu": "Mostrar _MENU_ registros",
                    "sZeroRecords": "Não foram encontrados resultados",
                    "sInfo": "Mostrando de _START_ até _END_ de _TOTAL_ registro(s)",
                    "sInfoEmpty": "Mostrando de 0 até 0 de 0 registro(s)",
                    "sInfoFiltered": "(filtrado de _MAX_ registros no total)",
                    "sInfoPostFix": "",
                    "sSearch": "Procurar:",
                    "sUrl": "",
                    "oPaginate": {
                        "sFirst": "Primeiro",
                        "sPrevious": "Anterior",
                        "sNext": "Próximo",
                        "sLast": "Último"
                    },
                    "oAria": {
                        "sSortAscending": ": Ordenar colunas de forma ascendente",
                        "sSortDescending": ": Ordenar colunas de forma descendente"
                    }
                },
                pageLength: 3,
                lengthMenu: [3, 10, 15],
                ordering: false
            };

            $('#categoriesTable').DataTable(tableConfig);

            $('#productsTable').DataTable(tableConfig);
        });

        function setModalTitle(modal, title) {
            $(modal + " .modal-title").text(title);
        }
    </script>
}

WK.TechnicalTest.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WK</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.2.1/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WK.TechnicalTest.Web.styles.css" asp-append-version="true" />

    @await RenderSectionAsync("Styles", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img height="33" src="~/images/Logo-02.png" />
                </a>
               
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.2.1/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>